export type DietaryStatus = "veg" | "non-veg" | "egg";
export interface MenuItem {
  id: string; name: string; category: string; subcategory?: string;
  description?: string; price?: number | string;
  variants?: { label: string; price: number | string; }[];
  tags?: Array<"veg"|"non-veg"|"egg"|"prawn"|"fish"|"popular"|"spicy"|"new"|"combo">;
}
export const menuCategories = [
  "Hot Beverages","Tea","Cold Beverages","Shakes & Smoothies",
  "Snacks & Starters","Burgers","Sandwiches & Bruschetta",
  "Pasta & Spaghetti","Wraps & Quesadilla","Chinese","Indian","Desserts","Add-ons"
];
export const menuData: MenuItem[] = [
  // HOT BEVERAGES - Coffee
  {id:"hb1",name:"Single Shot Espresso",category:"Hot Beverages",subcategory:"Coffee",price:40,tags:["veg"],description:"A concentrated shot of perfectly extracted espresso é bold, intense, and soul-awakening."},
  {id:"hb2",name:"Double Shot Espresso",category:"Hot Beverages",subcategory:"Coffee",price:60,tags:["veg"],description:"Two shots of rich espresso for when you need that extra push. Smooth yet powerful."},
  {id:"hb3",name:"Americano (Single Shot)",category:"Hot Beverages",subcategory:"Coffee",price:50,tags:["veg"],description:"Espresso mellowed with hot water é clean, light, and endlessly comforting."},
  {id:"hb4",name:"Americano (Double Shot)",category:"Hot Beverages",subcategory:"Coffee",price:80,tags:["veg"],description:"Double the depth, double the warmth. A bold cup for serious coffee lovers."},
  {id:"hb5",name:"Cappuccino (Single Shot)",category:"Hot Beverages",subcategory:"Coffee",price:80,tags:["veg"],description:"Silky steamed milk foam over a shot of espresso é the classic café ritual."},
  {id:"hb6",name:"Cappuccino (Double Shot)",category:"Hot Beverages",subcategory:"Coffee",price:120,tags:["veg","popular"],description:"Extra espresso beneath a cloud of velvety foam. A café favourite worth every sip."},
  {id:"hb7",name:"Café Mocha",category:"Hot Beverages",subcategory:"Coffee",price:110,tags:["veg"],description:"Espresso meets rich chocolate in a warm, indulgent hug of a drink."},
  {id:"hb8",name:"Cappuccino with Whipped Cream",category:"Hot Beverages",subcategory:"Coffee",price:110,tags:["veg"],description:"Your favourite cappuccino crowned with a swirl of luscious whipped cream."},
  {id:"hb9",name:"Cappuccino with Caramel",category:"Hot Beverages",subcategory:"Coffee",price:120,tags:["veg"],description:"Espresso and foam elevated with a golden drizzle of caramel é sweet, smooth, irresistible."},
  {id:"hb10",name:"Cappuccino with Caramel & Whipped Cream",category:"Hot Beverages",subcategory:"Coffee",price:130,tags:["veg"],description:"The full indulgence é caramel, cream, and espresso in one beautiful cup."},
  {id:"hb11",name:"Cappuccino Takeaway",category:"Hot Beverages",subcategory:"Coffee",price:120,tags:["veg"],description:"Your café experience, on the go. Perfectly packed for wherever life takes you."},
  {id:"hb12",name:"Cappuccino with Roasted Hazelnut",category:"Hot Beverages",subcategory:"Coffee",price:130,tags:["veg"],description:"A nutty, aromatic twist on the classic é roasted hazelnut makes every sip memorable."},
  // TEA - Without Milk
  {id:"t1",name:"Darjeeling 2nd Flush",category:"Tea",subcategory:"Without Milk",price:60,tags:["veg"],description:"India's finest é a golden cup with a muscatel character that tea lovers dream about."},
  {id:"t2",name:"Blue Tea",category:"Tea",subcategory:"Without Milk",price:60,tags:["veg"],description:"A naturally striking blue brew from butterfly pea flowers é as beautiful as it is calming."},
  {id:"t3",name:"Black Tea",category:"Tea",subcategory:"Without Milk",price:40,tags:["veg"],description:"Pure, simple, and classic. The perfect cup to anchor your day."},
  {id:"t4",name:"Lemon Tea",category:"Tea",subcategory:"Without Milk",price:40,tags:["veg"],description:"Bright and refreshing with a citrus lift é a gentle pick-me-up anytime."},
  {id:"t5",name:"Lemon Tea with Honey",category:"Tea",subcategory:"Without Milk",price:50,tags:["veg"],description:"Lemon's tang softened by the warmth of natural honey é soothing and delightful."},
  {id:"t6",name:"Green Tea",category:"Tea",subcategory:"Without Milk",price:40,tags:["veg"],description:"Light, clean, and full of calm energy. The mindful choice."},
  {id:"t7",name:"Green Tea with Lemon",category:"Tea",subcategory:"Without Milk",price:50,tags:["veg"],description:"A fresh citrus note brightens every sip of this clean, healthful brew."},
  {id:"t8",name:"Green Tea with Lemon & Honey",category:"Tea",subcategory:"Without Milk",price:55,tags:["veg"],description:"The perfect wellness drink é light, balanced, and naturally sweet."},
  // TEA - Chai
  {id:"t9",name:"Karak Chai",category:"Tea",subcategory:"Chai",tags:["veg"],description:"Strong, spiced, and deeply satisfying é a chai that means business.",variants:[{label:"Cup",price:55},{label:"Pot",price:210}]},
  {id:"t10",name:"Masala Tea",category:"Tea",subcategory:"Chai",tags:["veg"],description:"A fragrant blend of spices and tea that warms you from the inside out.",variants:[{label:"Cup",price:60},{label:"Pot",price:230}]},
  {id:"t11",name:"Saffron & Cardamom Tea",category:"Tea",subcategory:"Chai",tags:["veg"],description:"Exotic saffron and aromatic cardamom é a regal chai experience worth lingering over.",variants:[{label:"Cup",price:70},{label:"Pot",price:270}]},
  // COLD BEVERAGES - Mocktails
  {id:"cb1",name:"Classic Mint Mojito",category:"Cold Beverages",subcategory:"Mocktails",price:120,tags:["veg"],description:"Cool mint, a hint of lime, and a perfectly fizzy base é pure, refreshing bliss."},
  {id:"cb2",name:"Heavenly Blue Mojito",category:"Cold Beverages",subcategory:"Mocktails",price:120,tags:["veg","popular"],description:"A stunning blue butterfly pea mojito é it tastes as magical as it looks."},
  {id:"cb3",name:"Strawberry Mojito",category:"Cold Beverages",subcategory:"Mocktails",price:120,tags:["veg"],description:"Sun-ripened strawberry sweetness swirled into a chilled, minty fizz."},
  {id:"cb4",name:"Spicy Fizz",category:"Cold Beverages",subcategory:"Mocktails",price:120,tags:["veg","spicy"],description:"A fiery kick in every sip é the thrill-seeker's choice of mocktail."},
  {id:"cb5",name:"Ice Spice Fizz",category:"Cold Beverages",subcategory:"Mocktails",price:120,tags:["veg","spicy"],description:"Icy cold meets a bold spice hit é the kind of drink that makes you sit up straight."},
  {id:"cb6",name:"Refreshing Cucumber",category:"Cold Beverages",subcategory:"Mocktails",price:120,tags:["veg"],description:"Crisp cucumber steeped in cool mint é calm, clean, and incredibly refreshing."},
  {id:"cb7",name:"Spicy Cucumber",category:"Cold Beverages",subcategory:"Mocktails",price:120,tags:["veg","spicy"],description:"Cucumber's cool charm meets a surprising chilli edge. Unexpectedly addictive."},
  {id:"cb8",name:"Green Apple Virgin Mojito",category:"Cold Beverages",subcategory:"Premium Mocktails",price:120,tags:["veg"],description:"Tart green apple and cool mint é a vibrant, zingy mojito that dances on the palate."},
  {id:"cb9",name:"Blushing Rose Fizz",category:"Cold Beverages",subcategory:"Premium Mocktails",price:120,tags:["veg"],description:"Delicate rose with a sparkling lift é a romantic, floral drink worth blushing over."},
  {id:"cb10",name:"Kiwi Cooler",category:"Cold Beverages",subcategory:"Premium Mocktails",price:120,tags:["veg"],description:"Tangy kiwi in a frosty glass é bright, exotic, and utterly refreshing."},
  {id:"cb11",name:"Spicy Mango Cooler",category:"Cold Beverages",subcategory:"Premium Mocktails",price:120,tags:["veg","spicy"],description:"The tropical sweetness of mango with a fiery chilli tail é summer in a glass."},
  {id:"cb12",name:"Pan Mojito",category:"Cold Beverages",subcategory:"Premium Mocktails",price:120,tags:["veg"],description:"A desi twist on the classic é the nostalgia of pan in a cool, sparkling mojito."},
  {id:"cb13",name:"Teen Age Beer",category:"Cold Beverages",subcategory:"Premium Mocktails",price:120,tags:["veg"],description:"All the fun of the vibe, zero per cent é a chilled, bubbly drink that just hits right."},
  {id:"cb14",name:"Blueberry Cooler",category:"Cold Beverages",subcategory:"Premium Mocktails",price:120,tags:["veg"],description:"Sweet blueberries in a chilled, fizzy base é beautiful in colour, bold in flavour."},
  // COLD BEVERAGES - Iced Drinks
  {id:"cb15",name:"Ice Cappuccino",category:"Cold Beverages",subcategory:"Coolers & Iced Drinks",price:100,tags:["veg"],description:"Your favourite cappuccino é chilled over ice for those warm, coffee-craving moments."},
  {id:"cb16",name:"Lemon Mint Ice Tea",category:"Cold Beverages",subcategory:"Coolers & Iced Drinks",price:90,tags:["veg"],description:"Crisp iced tea with fresh lemon and cool mint é the ultimate afternoon refresher."},
  {id:"cb17",name:"Strawberry Ice Tea",category:"Cold Beverages",subcategory:"Coolers & Iced Drinks",price:90,tags:["veg"],description:"Fruity strawberry swirled into chilled tea é light, sweet, and endlessly sippable."},
  {id:"cb18",name:"Peach Ice Tea",category:"Cold Beverages",subcategory:"Coolers & Iced Drinks",price:90,tags:["veg"],description:"The gentle sweetness of peach in a chilled, perfectly brewed tea. Sublime."},
  {id:"cb19",name:"Watermelon Ice Tea",category:"Cold Beverages",subcategory:"Coolers & Iced Drinks",price:95,tags:["veg"],description:"Summer's favourite fruit transformed into a cool, thirst-quenching iced tea."},
  {id:"cb20",name:"Lemon Mint Honey Green Tea Ice Tea",category:"Cold Beverages",subcategory:"Coolers & Iced Drinks",price:105,tags:["veg"],description:"A wellness trio é green tea, lemon zest, and honey over ice. Refreshing and nourishing."},
  {id:"cb21",name:"Wildberry Ice Tea",category:"Cold Beverages",subcategory:"Coolers & Iced Drinks",price:105,tags:["veg"],description:"A medley of wild berries steeped into chilled tea é complex, fruity, unforgettable."},
  {id:"cb22",name:"Ice Americano",category:"Cold Beverages",subcategory:"Coolers & Iced Drinks",price:90,tags:["veg"],description:"Bold espresso over ice é the minimalist's iced coffee, clean and deeply satisfying."},
  // SHAKES & SMOOTHIES
  {id:"sm1",name:"Mango Delight",category:"Shakes & Smoothies",subcategory:"Smoothies",price:130,tags:["veg"],description:"Thick, sweet mango blended to perfection é liquid sunshine in a glass."},
  {id:"sm2",name:"Strawberry Slush",category:"Shakes & Smoothies",subcategory:"Smoothies",price:130,tags:["veg"],description:"Icy, vibrant, and naturally sweet é a strawberry slush that feels like a treat."},
  {id:"sm3",name:"Choco Splash",category:"Shakes & Smoothies",subcategory:"Smoothies",price:150,tags:["veg","popular"],description:"A rich chocolate smoothie that feels indulgent without the guilt. Crowd favourite."},
  {id:"sm4",name:"Caramel Delight",category:"Shakes & Smoothies",subcategory:"Smoothies",price:150,tags:["veg"],description:"Smooth caramel swirled into a thick, dreamy blend é comfort in every sip."},
  {id:"sm5",name:"Rose Love",category:"Shakes & Smoothies",subcategory:"Smoothies",price:170,tags:["veg"],description:"Delicate rose flavour in a velvety smooth blend é romantic, fragrant, and beautiful."},
  {id:"sm6",name:"Pan Shot",category:"Shakes & Smoothies",subcategory:"Smoothies",price:160,tags:["veg"],description:"The beloved flavour of pan reimagined as a chilled smoothie. Uniquely TSB."},
  {id:"sm7",name:"Cold Coffee (Without Ice Cream)",category:"Shakes & Smoothies",subcategory:"Cold Coffee",price:160,tags:["veg"],description:"Chilled, blended coffee é smooth and bold. The classic cold coffee done right."},
  {id:"sm8",name:"Cold Coffee with Ice Cream",category:"Shakes & Smoothies",subcategory:"Cold Coffee",price:170,tags:["veg"],description:"Cold coffee meets a scoop of creamy ice cream é dessert and drink in one."},
  {id:"sm9",name:"Cold Coffee with Whipped Cream",category:"Shakes & Smoothies",subcategory:"Cold Coffee",price:170,tags:["veg"],description:"A chilled coffee topped with a generous cloud of whipped cream. Pure luxury."},
  {id:"sm10",name:"Cold Coffee with Brownie",category:"Shakes & Smoothies",subcategory:"Cold Coffee",price:180,tags:["veg","popular"],description:"The ultimate duo é cold coffee paired with a rich fudgy brownie. Dangerously good."},
  {id:"sm11",name:"Chocolate Freak Shake",category:"Shakes & Smoothies",subcategory:"Freak Shakes",price:250,tags:["veg"],description:"An over-the-top chocolate extravaganza é thick, decadent, and absolutely unforgettable."},
  {id:"sm12",name:"Strawberry Freak Shake",category:"Shakes & Smoothies",subcategory:"Freak Shakes",price:250,tags:["veg"],description:"A towering strawberry spectacle é indulgent, fun, and made for the adventurous."},
  {id:"sm13",name:"Brownie Magic",category:"Shakes & Smoothies",subcategory:"Frappuccino",price:190,tags:["veg"],description:"Blended coffee with brownie pieces é a frosty, coffee-lover's dream dessert."},
  {id:"sm14",name:"Oreo Shake",category:"Shakes & Smoothies",subcategory:"Frappuccino",price:190,tags:["veg"],description:"Crushed Oreo cookies blended into a thick, creamy shake. Absolutely irresistible."},
  {id:"sm15",name:"Popcorn Shake",category:"Shakes & Smoothies",subcategory:"Frappuccino",price:190,tags:["veg"],description:"The playful sweetness of caramel popcorn in a chilled, creamy shake. Cinema vibes."},
  {id:"sm16",name:"Bubblegum Shake",category:"Shakes & Smoothies",subcategory:"Frappuccino",price:180,tags:["veg"],description:"Nostalgic bubblegum flavour in a frothy, colourful shake é pure joy in a glass."},
  {id:"sm17",name:"Red Velvet Shake",category:"Shakes & Smoothies",subcategory:"Frappuccino",price:190,tags:["veg"],description:"Lush red velvet flavour in a velvety smooth shake é as classy as it gets."},
  {id:"sm18",name:"Cheesecake Frappuccino",category:"Shakes & Smoothies",subcategory:"Frappuccino",price:190,tags:["veg"],description:"The creamy, tangy soul of cheesecake blended into a chilled frap. Heaven."},
  {id:"sm19",name:"Blueberry Frappuccino",category:"Shakes & Smoothies",subcategory:"Frappuccino",price:190,tags:["veg"],description:"Wild blueberries swirled into a thick, frosty frappuccino. Bold colour, bolder flavour."},
  // SNACKS & STARTERS - Fish & Prawns
  {id:"fp1",name:"Fish Fry",category:"Snacks & Starters",subcategory:"Fish & Prawns",price:200,tags:["non-veg","fish"],description:"Crispy on the outside, tender and flaky within é a classic done with real care."},
  {id:"fp2",name:"Fish Kabiraji",category:"Snacks & Starters",subcategory:"Fish & Prawns",price:220,tags:["non-veg","fish"],description:"A Bengali icon é fish encased in a delicate egg net, fried golden to perfection."},
  {id:"fp3",name:"Dry Chilli Fish",category:"Snacks & Starters",subcategory:"Fish & Prawns",price:225,tags:["non-veg","fish","spicy"],description:"Bold chilli, aromatic spices, and perfectly fried fish é a starter that commands attention."},
  {id:"fp4",name:"Fish Finger",category:"Snacks & Starters",subcategory:"Fish & Prawns",price:225,tags:["non-veg","fish"],description:"Six golden, crispy fish fingers é light, satisfying, and endlessly snackable."},
  {id:"fp5",name:"Fish & Chips",category:"Snacks & Starters",subcategory:"Fish & Prawns",price:230,tags:["non-veg","fish"],description:"The timeless classic é crispy fish alongside perfectly fried chips. Comfort food perfected."},
  {id:"fp6",name:"Golden Fried Prawns",category:"Snacks & Starters",subcategory:"Fish & Prawns",price:230,tags:["non-veg","prawn"],description:"Juicy prawns in a golden, crunchy coat é a seafood lover's irresistible starter."},
  {id:"fp7",name:"Dry Chilli Prawns",category:"Snacks & Starters",subcategory:"Fish & Prawns",price:240,tags:["non-veg","prawn","spicy"],description:"Plump prawns tossed in fiery chilli and aromatic spices é bold, fresh, magnificent."},
  // SNACKS - Veg
  {id:"sn1",name:"Dry Schezwan Babycorn",category:"Snacks & Starters",subcategory:"Veg Snacks",price:150,tags:["veg","spicy"],description:"Crunchy babycorn in a punchy schezwan sauce é the perfect shareable starter."},
  {id:"sn2",name:"Dry Chilli Babycorn",category:"Snacks & Starters",subcategory:"Veg Snacks",price:150,tags:["veg","spicy"],description:"Tender babycorn tossed in vibrant chilli sauce é crispy, spicy, and addictive."},
  {id:"sn3",name:"Paneer Pakora",category:"Snacks & Starters",subcategory:"Veg Snacks",price:180,tags:["veg"],description:"Soft paneer in a spiced, crispy batter é the snack everyone reaches for first."},
  {id:"sn4",name:"Dry Chilli Paneer",category:"Snacks & Starters",subcategory:"Veg Snacks",price:180,tags:["veg","spicy"],description:"Crispy paneer bites tossed in a bold chilli sauce é a timeless café favourite."},
  {id:"sn5",name:"Paneer Manchurian",category:"Snacks & Starters",subcategory:"Veg Snacks",price:190,tags:["veg"],description:"Golden fried paneer in a tangy, savory Manchurian glaze. Utterly moreish."},
  {id:"sn6",name:"Honey Chilli Paneer",category:"Snacks & Starters",subcategory:"Veg Snacks",price:180,tags:["veg","spicy"],description:"The beautiful balance of sweet honey and fiery chilli over crispy paneer. A crowd pleaser."},
  {id:"sn7",name:"Chilli Potato",category:"Snacks & Starters",subcategory:"Veg Snacks",price:170,tags:["veg","spicy"],description:"Crispy potato tossed in a punchy chilli sauce é the snack you didn't know you needed."},
  {id:"sn8",name:"Honey Chilli Potato",category:"Snacks & Starters",subcategory:"Veg Snacks",price:170,tags:["veg","spicy"],description:"Sweet, sticky honey meets a spicy chilli kick on perfectly crispy potatoes."},
  {id:"sn9",name:"Chilli Mushroom",category:"Snacks & Starters",subcategory:"Veg Snacks",price:150,tags:["veg","spicy"],description:"Earthy mushrooms transformed by a bold chilli toss é flavourful and deeply satisfying."},
  {id:"sn10",name:"Creamy Cheese Corn Mushroom",category:"Snacks & Starters",subcategory:"Veg Snacks",price:180,tags:["veg"],description:"Mushrooms, sweet corn, and melted cheese in a rich creamy blend. Warm and indulgent."},
  // SNACKS - Chicken
  {id:"ch1",name:"Crispy Chicken & Chips",category:"Snacks & Starters",subcategory:"Chicken Snacks",price:180,tags:["non-veg"],description:"Juicy, crispy chicken alongside golden chips é a satisfying duo that never disappoints."},
  {id:"ch2",name:"Chicken Popcorn",category:"Snacks & Starters",subcategory:"Chicken Snacks",price:180,tags:["non-veg"],description:"Bite-sized, perfectly seasoned, and irresistibly crunchy é the snack you can't stop eating."},
  {id:"ch3",name:"Chicken Dynamite",category:"Snacks & Starters",subcategory:"Chicken Snacks",price:180,tags:["non-veg","popular"],description:"Our bestselling starter é crispy chicken in a bold, flavour-packed dynamite sauce. A must-try."},
  {id:"ch4",name:"Chilli Chicken",category:"Snacks & Starters",subcategory:"Chicken Snacks",price:190,tags:["non-veg","spicy"],description:"A classic for a reason é tender chicken in a fiery, aromatic chilli sauce."},
  {id:"ch5",name:"Dragon Chicken",category:"Snacks & Starters",subcategory:"Chicken Snacks",price:210,tags:["non-veg","spicy"],description:"A fiery, flavour-intense dry chicken preparation that's as exciting as it sounds."},
  {id:"ch6",name:"Chicken Manchurian",category:"Snacks & Starters",subcategory:"Chicken Snacks",price:190,tags:["non-veg"],description:"Juicy chicken dumplings in a savory, tangy Manchurian sauce é deeply comforting."},
  {id:"ch7",name:"Chicken Honey Chilli",category:"Snacks & Starters",subcategory:"Chicken Snacks",price:190,tags:["non-veg","spicy"],description:"The irresistible combo of sweet honey and fierce chilli on perfectly cooked chicken."},
  // BURGERS
  {id:"bg1",name:"Classic Mayo Burger (Veg)",category:"Burgers",price:120,tags:["veg"],description:"A satisfying, well-built veg burger with our house mayo é simple, reliable, delicious."},
  {id:"bg2",name:"Classic Mayo Burger (Chicken)",category:"Burgers",price:135,tags:["non-veg","popular"],description:"Tender chicken with our signature mayo in a soft bun é the burger that started it all."},
  {id:"bg3",name:"Honey Mustard Burger",category:"Burgers",price:150,tags:["veg"],description:"Sweet honey mustard brings a beautiful complexity to this standout vegetarian burger."},
  {id:"bg4",name:"TSB Special Burger",category:"Burgers",price:140,tags:["popular"],description:"Our signature creation é a layered, flavour-packed burger that defines the TSB experience.",variants:[{label:"Veg",price:140},{label:"Chicken",price:155}]},
  {id:"bg5",name:"Injected Cheese Burger",category:"Burgers",price:180,tags:["non-veg"],description:"Oozing with cheese from the inside out é a gloriously indulgent burger experience."},
  {id:"bg6",name:"Veg Pizza Burger",category:"Burgers",price:140,tags:["veg"],description:"Two favourites collide é pizza flavours in a soft, stacked burger. Surprisingly brilliant."},
  {id:"bg7",name:"Chicken Pizza Burger",category:"Burgers",price:160,tags:["non-veg"],description:"Juicy chicken meets pizza-inspired toppings in a burger that breaks all the rules."},
  {id:"bg8",name:"Nachos Cheese Burger",category:"Burgers",price:140,tags:["veg"],description:"Crunchy nachos and melted cheese piled into a burger é a textural masterpiece."},
  {id:"bg9",name:"Cheese Burger",category:"Burgers",price:150,tags:["veg"],description:"Golden-melted cheese layered into a beautifully assembled, satisfying burger."},
  {id:"bg10",name:"Double Chicken Cheese Burger",category:"Burgers",price:190,tags:["non-veg","popular"],description:"Double the chicken, double the cheese, double the joy. For the truly hungry."},
  {id:"bg11",name:"Korean Sweet Chilli Burger",category:"Burgers",price:170,tags:["non-veg","spicy"],description:"Inspired by Korean flavours é a punchy, sweet-spicy glaze on juicy chicken. Addictive."},
  {id:"bg12",name:"Chicken Chilli Habanero Burger",category:"Burgers",price:160,tags:["non-veg","spicy"],description:"For those who dare é habanero heat on crispy chicken. Bold, intense, unforgettable."},
  {id:"bg13",name:"Spicy Garlic Chicken Burger",category:"Burgers",price:160,tags:["non-veg","spicy"],description:"Roasted garlic and chilli on juicy chicken é a bold, aromatic burger worth craving."},
  {id:"bg14",name:"Prawn Burger",category:"Burgers",price:180,tags:["non-veg","prawn"],description:"Succulent prawns in a premium burger é a seafood twist that's genuinely special."},
  // SANDWICHES & BRUSCHETTA
  {id:"sw1",name:"Classic Mayo Sandwich (Veg)",category:"Sandwiches & Bruschetta",subcategory:"Sandwiches",price:105,tags:["veg"],description:"Fresh, stacked, and satisfying é our house mayo brings this classic veg sandwich to life."},
  {id:"sw2",name:"Chicken Mayo Sandwich",category:"Sandwiches & Bruschetta",subcategory:"Sandwiches",price:135,tags:["non-veg","popular"],description:"Tender chicken layered with creamy mayo in perfectly toasted bread. A TSB staple."},
  {id:"sw3",name:"Honey Mustard Sandwich",category:"Sandwiches & Bruschetta",subcategory:"Sandwiches",price:150,tags:["veg"],description:"Sweet honey mustard adds a gourmet touch to this beautifully layered sandwich."},
  {id:"sw4",name:"TSB Special Sandwich",category:"Sandwiches & Bruschetta",subcategory:"Sandwiches",price:140,tags:["popular"],description:"Our chef's signature sandwich é a flavour-packed combination that keeps people coming back.",variants:[{label:"Veg",price:140},{label:"Chicken",price:155}]},
  {id:"sw5",name:"Cheese Corn Sandwich",category:"Sandwiches & Bruschetta",subcategory:"Sandwiches",price:125,tags:["veg"],description:"Sweet corn and melted cheese é a warm, comforting sandwich that feels like a hug."},
  {id:"sw6",name:"Chicken Sausage Sandwich",category:"Sandwiches & Bruschetta",subcategory:"Sandwiches",price:190,tags:["non-veg"],description:"Juicy chicken sausage layered into a premium sandwich. Hearty and full of flavour."},
  {id:"br1",name:"Honey Mustard Bruschetta",category:"Sandwiches & Bruschetta",subcategory:"Bruschetta",price:140,tags:["veg"],description:"Toasted artisan bread with a sweet honey mustard spread é elegant, simple, stunning."},
  {id:"br2",name:"Classic Mayo Bruschetta",category:"Sandwiches & Bruschetta",subcategory:"Bruschetta",price:140,tags:["veg"],description:"Crispy toasted bread with our house mayo and fresh toppings é a café classic."},
  {id:"br3",name:"TSB Special Bruschetta",category:"Sandwiches & Bruschetta",subcategory:"Bruschetta",price:140,tags:["veg","popular"],description:"Our signature bruschetta, loaded with our special blend. One bite and you'll understand why it's the favourite."},
  {id:"br4",name:"Pizza Bruschetta",category:"Sandwiches & Bruschetta",subcategory:"Bruschetta",price:160,tags:["veg"],description:"All the joy of pizza on crispy toasted bread é a satisfying, cheesy bruschetta twist."},
  {id:"br5",name:"Green Apple Prawn Bruschetta",category:"Sandwiches & Bruschetta",subcategory:"Bruschetta",price:200,tags:["non-veg","prawn"],description:"Plump prawns and tangy green apple on toasted bread é a sophisticated, premium choice."},
  // PASTA & SPAGHETTI
  {id:"ps1",name:"White Sauce Pasta",category:"Pasta & Spaghetti",subcategory:"Pasta",price:165,tags:["veg","popular"],description:"Silky, creamy béchamel sauce coating perfectly cooked pasta é comfort food at its finest."},
  {id:"ps2",name:"Red Sauce Pasta",category:"Pasta & Spaghetti",subcategory:"Pasta",price:160,tags:["veg"],description:"A rich, vibrant tomato sauce with herbs and pasta é a warm Italian classic."},
  {id:"ps3",name:"Schezwan Pasta",category:"Pasta & Spaghetti",subcategory:"Pasta",price:160,tags:["veg","spicy"],description:"East meets Italy é a bold schezwan sauce gives this pasta an exciting, fiery edge."},
  {id:"ps4",name:"Peri Peri Pasta",category:"Pasta & Spaghetti",subcategory:"Pasta",price:175,tags:["veg","spicy"],description:"Vibrant peri peri sauce tossed through pasta é a spicy, tangy twist you'll love."},
  {id:"ps5",name:"Mixed Sauce Pasta",category:"Pasta & Spaghetti",subcategory:"Pasta",price:175,tags:["veg"],description:"Red and white sauces blended into one luxuriously satisfying pasta preparation."},
  {id:"ps6",name:"Chicken Keema Pasta",category:"Pasta & Spaghetti",subcategory:"Pasta",price:195,tags:["non-veg"],description:"Spiced chicken mince folded into pasta é a hearty, deeply flavourful preparation."},
  {id:"ps7",name:"Prawn Pasta",category:"Pasta & Spaghetti",subcategory:"Pasta",price:200,tags:["non-veg","prawn"],description:"Plump, juicy prawns tossed through creamy pasta é a luxurious, must-try dish."},
  {id:"sp1",name:"Chicken Keema Spaghetti",category:"Pasta & Spaghetti",subcategory:"Spaghetti",price:195,tags:["non-veg"],description:"Long, silky spaghetti with a richly spiced chicken mince sauce. Deeply comforting."},
  {id:"sp2",name:"Paneer Spaghetti",category:"Pasta & Spaghetti",subcategory:"Spaghetti",price:190,tags:["veg"],description:"Soft paneer and aromatic spices wound through spaghetti é desi soul, Italian heart."},
  {id:"sp3",name:"Mushroom Alfredo Spaghetti",category:"Pasta & Spaghetti",subcategory:"Spaghetti",price:185,tags:["veg"],description:"Earthy mushrooms in a velvety Alfredo sauce over spaghetti. Elegant and deeply satisfying."},
  {id:"sp4",name:"Prawn Spaghetti",category:"Pasta & Spaghetti",subcategory:"Spaghetti",price:230,tags:["non-veg","prawn"],description:"Succulent prawns and aromatic sauce over long spaghetti é a premium, restaurant-worthy dish."},
  // WRAPS & QUESADILLA
  {id:"wr1",name:"Spicy Chicken Wrap",category:"Wraps & Quesadilla",subcategory:"Wraps",price:160,tags:["non-veg","spicy","popular"],description:"Fiery spiced chicken wrapped in a soft tortilla é a handheld meal full of bold flavour."},
  {id:"wr2",name:"Paneer Wrap",category:"Wraps & Quesadilla",subcategory:"Wraps",price:160,tags:["veg"],description:"Flavourful paneer wrapped with fresh veggies and sauce é satisfying and full of character."},
  {id:"wr3",name:"Peri Peri Wrap",category:"Wraps & Quesadilla",subcategory:"Wraps",price:170,tags:["spicy"],description:"Tangy peri peri sauce with your choice of filling é a zesty, vibrant wrap.",variants:[{label:"Chicken",price:170},{label:"Paneer",price:160}]},
  {id:"wr4",name:"Mumbai Style Pav Bhaji Wrap",category:"Wraps & Quesadilla",subcategory:"Wraps",price:155,tags:["veg"],description:"The streets of Mumbai in a wrap é spiced pav bhaji filling rolled into a soft tortilla."},
  {id:"wr5",name:"Chilli Garlic Wrap",category:"Wraps & Quesadilla",subcategory:"Wraps",price:155,tags:["spicy"],description:"Aromatic chilli garlic sauce with a satisfying filling é bold, punchy, and brilliant.",variants:[{label:"Chicken",price:155},{label:"Paneer",price:145}]},
  {id:"wr6",name:"Prawn Wrap",category:"Wraps & Quesadilla",subcategory:"Wraps",price:210,tags:["non-veg","prawn"],description:"Tender, seasoned prawns in a soft wrap é a premium, seafood-lover's delight."},
  {id:"qw1",name:"TSB Special Quesadilla",category:"Wraps & Quesadilla",subcategory:"Quesadilla",price:175,tags:["popular"],description:"Our signature quesadilla é a crispy, golden, cheese-loaded masterpiece. The best in Rampurhat.",variants:[{label:"Chicken",price:175},{label:"Paneer",price:165}]},
  {id:"qw2",name:"Classic Mayo Quesadilla",category:"Wraps & Quesadilla",subcategory:"Quesadilla",price:140,tags:["veg"],description:"Crispy tortilla sealed with melted cheese and creamy mayo. Simple, perfect comfort food."},
  {id:"qw3",name:"Honey Mustard Quesadilla",category:"Wraps & Quesadilla",subcategory:"Quesadilla",price:170,tags:["veg"],description:"A golden quesadilla with a sweet honey mustard filling é beautifully balanced."},
  {id:"qw4",name:"Chicken Habanero Quesadilla",category:"Wraps & Quesadilla",subcategory:"Quesadilla",price:175,tags:["non-veg","spicy"],description:"Fiery habanero and chicken sealed in a crispy, melted-cheese quesadilla. For the brave."},
  // CHINESE
  {id:"cn1",name:"Veg Hakka Noodles",category:"Chinese",subcategory:"Noodles",price:110,tags:["veg"],description:"Wok-tossed hakka noodles with fresh vegetables é light, flavourful, and satisfying."},
  {id:"cn2",name:"Egg Hakka Noodles",category:"Chinese",subcategory:"Noodles",price:130,tags:["egg"],description:"Classic hakka noodles elevated with egg é a satisfying, protein-rich bowl."},
  {id:"cn3",name:"Chicken Hakka Noodles",category:"Chinese",subcategory:"Noodles",price:175,tags:["non-veg","popular"],description:"Wok-fired noodles with juicy chicken pieces é the Chinese dish everyone loves."},
  {id:"cn4",name:"Mixed Noodles",category:"Chinese",subcategory:"Noodles",price:205,tags:["non-veg"],description:"A generous mix of everything é noodles tossed with chicken, egg, and vegetables."},
  {id:"cn5",name:"Veg Fried Rice",category:"Chinese",subcategory:"Fried Rice",price:125,tags:["veg"],description:"Lightly seasoned, perfectly wok-tossed fried rice with crisp vegetables."},
  {id:"cn6",name:"Egg Fried Rice",category:"Chinese",subcategory:"Fried Rice",price:140,tags:["egg"],description:"Golden egg scramble folded through aromatic fried rice é simple and irresistible."},
  {id:"cn7",name:"Chicken Fried Rice",category:"Chinese",subcategory:"Fried Rice",price:185,tags:["non-veg","popular"],description:"Juicy chicken pieces wok-tossed with fragrant fried rice é a complete, satisfying meal."},
  {id:"cn8",name:"Mixed Fried Rice",category:"Chinese",subcategory:"Fried Rice",price:205,tags:["non-veg"],description:"The ultimate fried rice é chicken, egg, and vegetables in one flavourful bowl."},
  {id:"cg1",name:"Chilli Chicken",category:"Chinese",subcategory:"Chinese Gravies",price:190,tags:["non-veg","spicy"],description:"A Chinese-Indian classic é juicy chicken in a fierce, tangy chilli gravy. Legendary."},
  {id:"cg2",name:"Chilli Paneer",category:"Chinese",subcategory:"Chinese Gravies",price:180,tags:["veg","spicy"],description:"Crispy paneer in a bold chilli gravy é the vegetarian dish that needs no introduction."},
  {id:"cg3",name:"Chilli Prawn",category:"Chinese",subcategory:"Chinese Gravies",price:230,tags:["non-veg","prawn","spicy"],description:"Plump prawns in a fiery, aromatic chilli sauce é a luxurious, bold preparation."},
  {id:"cg4",name:"Sweet & Sour Chicken",category:"Chinese",subcategory:"Chinese Gravies",price:195,tags:["non-veg"],description:"The perfect balance of sweet and tangy é a vibrant, crowd-pleasing Chinese favourite."},
  {id:"cg5",name:"Schezwan Chicken",category:"Chinese",subcategory:"Chinese Gravies",price:195,tags:["non-veg","spicy"],description:"Chicken in a rich, fiery schezwan sauce é bold, aromatic, and deeply satisfying."},
  // INDIAN
  {id:"in1",name:"Jeera Rice",category:"Indian",subcategory:"Rice",price:90,tags:["veg"],description:"Fragrant basmati rice tempered with golden cumin é simple, aromatic perfection."},
  {id:"in2",name:"Peas Rice",category:"Indian",subcategory:"Rice",price:110,tags:["veg"],description:"Soft basmati with sweet green peas é a gentle, comforting rice dish."},
  {id:"in3",name:"Bengali Fried Rice",category:"Indian",subcategory:"Rice",price:125,tags:["veg"],description:"A beloved Bengali classic é fragrant, lightly spiced fried rice with a homemade soul."},
  {id:"in4",name:"Paneer Matar Rice",category:"Indian",subcategory:"Rice",price:180,tags:["veg"],description:"Soft paneer and sweet peas in spiced, aromatic rice é a complete, satisfying meal."},
  {id:"in5",name:"Tawa Chicken Masala",category:"Indian",subcategory:"Gravies",price:200,tags:["non-veg","spicy"],description:"Chicken cooked on a hot tawa with robust Indian spices é intense, smoky, magnificent."},
  {id:"in6",name:"Paneer Masala",category:"Indian",subcategory:"Gravies",price:190,tags:["veg"],description:"Soft paneer in a rich, aromatic masala gravy é a comforting Indian classic."},
  {id:"in7",name:"Chicken Bharta",category:"Indian",subcategory:"Gravies",price:200,tags:["non-veg"],description:"Smoky, slow-cooked chicken in a bharta style é earthy, bold, and uniquely satisfying."},
  {id:"in8",name:"Paneer Bharta",category:"Indian",subcategory:"Gravies",price:170,tags:["veg"],description:"Paneer in a smoky bharta preparation é a rustic, flavour-rich vegetarian delight."},
  {id:"in9",name:"Mixed Veg Masala",category:"Indian",subcategory:"Gravies",price:160,tags:["veg"],description:"A wholesome medley of seasonal vegetables in a richly spiced masala gravy."},
  // DESSERTS
  {id:"ds1",name:"Strawberry Waffle",category:"Desserts",subcategory:"Waffles",price:130,tags:["veg"],description:"A crisp, golden waffle crowned with sweet strawberry é dessert happiness on a plate."},
  {id:"ds2",name:"Mango Waffle",category:"Desserts",subcategory:"Waffles",price:130,tags:["veg"],description:"Sunshine mango on a perfectly crisp waffle é a tropical dessert treat."},
  {id:"ds3",name:"Chocolate Waffle",category:"Desserts",subcategory:"Waffles",price:150,tags:["veg","popular"],description:"A golden waffle drenched in rich chocolate é the dessert lover's dream."},
  {id:"ds4",name:"Caramel Waffle",category:"Desserts",subcategory:"Waffles",price:150,tags:["veg"],description:"Golden caramel drizzled over a crisp, warm waffle é pure, buttery indulgence."},
  {id:"ds5",name:"Strawberry Sundae",category:"Desserts",subcategory:"Sundaes",price:120,tags:["veg"],description:"Creamy ice cream with sweet strawberry sauce é a timeless dessert delight."},
  {id:"ds6",name:"Mango Sundae",category:"Desserts",subcategory:"Sundaes",price:120,tags:["veg"],description:"Tropical mango over smooth ice cream é a sunny, joyful sundae."},
  {id:"ds7",name:"Chocolate Sundae",category:"Desserts",subcategory:"Sundaes",price:130,tags:["veg","popular"],description:"Rich chocolate sauce over creamy ice cream é the classic sundae, always perfect."},
  {id:"ds8",name:"Kiwi Sundae",category:"Desserts",subcategory:"Sundaes",price:120,tags:["veg"],description:"Tangy kiwi over silky ice cream é a refreshing, vibrant dessert choice."},
  {id:"ds9",name:"Caramel Sundae",category:"Desserts",subcategory:"Sundaes",price:130,tags:["veg"],description:"Warm caramel ribbons over cool ice cream é a heavenly contrast in every spoon."},
  {id:"ds10",name:"Pan Sundae",category:"Desserts",subcategory:"Sundaes",price:120,tags:["veg"],description:"The nostalgia of pan in a creamy sundae é a uniquely Indian dessert experience."},
  {id:"ds11",name:"Brownie",category:"Desserts",subcategory:"Brownies",price:150,tags:["veg"],description:"Fudgy, rich, and deeply chocolatey é our brownie is simply, seriously good."},
  {id:"ds12",name:"Brownie with Ice Cream",category:"Desserts",subcategory:"Brownies",price:140,tags:["veg","popular"],description:"Warm fudgy brownie meets cool, creamy ice cream é a dessert duet made in heaven."},
  {id:"ds13",name:"Sizzler Brownie",category:"Desserts",subcategory:"Brownies",price:180,tags:["veg"],description:"A theatrical, sizzling brownie experience é hot plate, cold ice cream, pure drama."},
  // ADD-ONS
  {id:"ad1",name:"Extra Mayo",category:"Add-ons",price:10,tags:["veg"],description:"A little extra of our creamy house mayo for your dish."},
  {id:"ad2",name:"Extra Cheese Slice",category:"Add-ons",price:30,tags:["veg"],description:"Because more cheese always makes everything better."},
  {id:"ad3",name:"Extra Chicken",category:"Add-ons",price:50,tags:["non-veg"],description:"Add an extra portion of chicken to any dish."},
  {id:"ad4",name:"Extra Fish Fry",category:"Add-ons",price:100,tags:["non-veg","fish"],description:"An extra piece of our crispy fried fish alongside your meal."},
  {id:"ad5",name:"Extra Ice Cream",category:"Add-ons",price:30,tags:["veg"],description:"An extra scoop of creamy ice cream for your dessert."},
  {id:"ad6",name:"Extra Sauce",category:"Add-ons",price:15,tags:["veg"],description:"Any of our signature sauces on the side é ask your server for options."},
];

